Porting from HotPi 7.

diff --git a/config/path b/config/path
--- a/config/path
+++ b/config/path
@@ -17,7 +17,7 @@ set -e
   fi
 
 HOST_NAME=`$LOCAL_CC -dumpmachine`
-TARGET_NAME=$(echo $TARGET_SUBARCH | sed -e "s,-,,")-openelec-linux-gnu${TARGET_ABI}
+TARGET_NAME=$TARGET_GCC_ARCH-openelec-linux-gnu${TARGET_ABI}
 
 BUILD=$BUILD_BASE.$DISTRONAME-$PROJECT.$TARGET_ARCH-$OPENELEC_VERSION
 if [ "$OPENELEC_VERSION" = "devel" ] ; then
@@ -40,7 +40,7 @@ SYSROOT_PREFIX=$ROOT/$TOOLCHAIN/$TARGET_NAME/sysroot
 LIB_PREFIX=$SYSROOT_PREFIX/usr
 TARGET_PREFIX=$ROOT/$TOOLCHAIN/bin/$TARGET_NAME-
 
-FAKEROOT_SCRIPT=$ROOT/.fakeroot.$PROJECT.$TARGET_ARCH
+FAKEROOT_SCRIPT=$ROOT/.fakeroot.$BUILD
 
 if [ -z "$INSTALL" ]; then
   INSTALL=$BUILD/image/system
@@ -61,6 +61,8 @@ SED="sed -i"
   PKG_LICENSE="unknown"
   PKG_SITE=""
   PKG_URL=""
+  PKG_GIT_URL=""
+  PKG_GIT_BRANCH=""
   PKG_DEPENDS_TARGET=""
   PKG_DEPENDS_HOST=""
   PKG_DEPENDS_INIT=""
@@ -77,7 +79,41 @@ SED="sed -i"
     _FOUND=0
     PKG_DIR=""
 
-    # first check project folder for a package
+    # check project folder for a package in home dir
+    for DIR in $(find $HOME/.openelec/projects/$PROJECT/packages -type d -name $_PKG_ROOT_NAME 2>/dev/null); do
+      if [ -r "$DIR/package.mk" ]; then
+        # found first, set $PKG_DIR
+        PKG_DIR="$DIR"
+        # keep track of dirs with package.mk for detecting multiple folders
+        _ALL_DIRS="${_ALL_DIRS}${DIR}\\n"
+        _FOUND=$((_FOUND+1))
+        if [ $_FOUND -gt 1 ]; then
+          # _FOUND more ? fail
+          echo "Error - multiple package folders:"
+          echo -e "$_ALL_DIRS"
+          exit 1
+        fi
+      fi
+    done
+
+    # check for a package in home dir if not found already
+    for DIR in $(find $HOME/.openelec/packages -type d -name $_PKG_ROOT_NAME 2>/dev/null); do
+      if [ -r "$DIR/package.mk" ]; then
+        # found first, set $PKG_DIR
+        PKG_DIR="$DIR"
+        # keep track of dirs with package.mk for detecting multiple folders
+        _ALL_DIRS="${_ALL_DIRS}${DIR}\\n"
+        _FOUND=$((_FOUND+1))
+        if [ $_FOUND -gt 1 ]; then
+          # _FOUND more ? fail
+          echo "Error - multiple package folders:"
+          echo -e "$_ALL_DIRS"
+          exit 1
+        fi
+      fi
+    done
+
+    # check project folder for a package if not found already
     for DIR in $(find $ROOT/projects/$PROJECT/packages -type d -name $_PKG_ROOT_NAME 2>/dev/null); do
       if [ -r "$DIR/package.mk" ]; then
         # found first, set $PKG_DIR
@@ -130,8 +166,6 @@ XORG_PATH_XKB_OUTPUT=/var/lib/xkb
 XORG_PATH_RGB=/usr/lib/X11/rgb
 XORG_PATH_MODULES=/usr/lib/xorg/modules
 XORG_PATH_DRIVERS=/usr/lib/xorg/modules/drivers
-
-SSL_CERTIFICATES="/etc/ssl"
 
 TOOLCHAIN_LANGUAGES=c
 [ "$TOOLCHAIN_CXX" = yes ] && TOOLCHAIN_LANGUAGES=${TOOLCHAIN_LANGUAGES},c++
diff --git a/scripts/extract b/scripts/extract
--- a/scripts/extract
+++ b/scripts/extract
@@ -2,7 +2,7 @@
 
 ################################################################################
 #      This file is part of OpenELEC - http://www.openelec.tv
-#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
+#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
 #
 #  OpenELEC is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -25,21 +25,27 @@ if [ -z "$3" ]; then
   exit 1
 fi
 
-[ -z "$PKG_URL" ] && exit 1
+[ -z "$PKG_URL" -a -z "$PKG_GIT_URL" ] && exit 1
 [ ! -d "$SOURCES/$1" -o ! -d "$3" ] && exit 1
 
-for i in $PKG_URL; do
-  FILE="`basename $i`"
+if [ -n "$PKG_URL" ]; then
+  for i in $PKG_URL; do
+    FILE="$FILE `basename $i`"
+  done
+elif [ -n "$PKG_GIT_URL" ]; then
+  FILE="$PKG_NAME-$PKG_VERSION.tar.xz"
+fi
 
-  case $FILE in
+for i in $FILE; do
+  case $i in
   $2)
-    f="$SOURCES/$1/$FILE"
+    f="$SOURCES/$1/$i"
     if [ ! -f $f ]; then
-      echo "error: File $FILE doesn't exists in package $1 sources directory"
+      echo "error: File $i doesn't exists in package $1 sources directory"
       echo "have you called scripts/extract before scripts/get ?"
       exit 1
     fi
-    case $FILE in
+    case $i in
       *.tar)
         tar xf $f -C $3
         ;;
@@ -57,8 +63,7 @@ for i in $PKG_URL; do
         7z x -o$3/$1 $f
         ;;
       *.zip)
-        mkdir -p $3/$1
-        unzip -q $f -d $3/$1
+        unzip -q $f -d $3
         ;;
       *.diff | *.patch)
         cat $f | patch -d $3 -p1
