Update based on OpenELEC 6.0

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -1,23 +1,23 @@
 #!/bin/sh
 
 ################################################################################
-#      This file is part of DeKockBlock - http://www.dekockblock.tv
-#      Copyright (C) 2009-2014 Stephan Raue (stephan@dekockblock.tv)
-#      Copyright (C) 2010-2011 Roman Weber (roman@dekockblock.tv)
+#      This file is part of OpenELEC - http://www.openelec.tv
+#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
+#      Copyright (C) 2010-2011 Roman Weber (roman@openelec.tv)
 #      Copyright (C) 2012 Yann Cézard (eesprit@free.fr)
 #
-#  DeKockBlock is free software: you can redistribute it and/or modify
+#  OpenELEC is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation, either version 2 of the License, or
 #  (at your option) any later version.
 #
-#  DeKockBlock is distributed in the hope that it will be useful,
+#  OpenELEC is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.
 #
 #  You should have received a copy of the GNU General Public License
-#  along with DeKockBlock.  If not, see <http://www.gnu.org/licenses/>.
+#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
 ################################################################################
 
   # create directories
@@ -55,8 +55,20 @@
   INSTALLED_MEMORY=`cat /proc/meminfo | grep 'MemTotal:' | awk '{print $2}'`
   SYSTEM_TORAM_LIMIT=1024000
 
+  LIVE="no"
+
   # hide kernel log messages on console
   echo '1 4 1 7' > /proc/sys/kernel/printk
+
+  # set ondemand up_threshold
+  if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold ] ; then
+    echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
+  fi
+
+  # run platform_init script if exists
+  if [ -f "./platform_init" ]; then
+    ./platform_init
+  fi
 
   # clear screen and hide cursor
   clear
@@ -123,6 +135,9 @@
         ;;
       noram)
         SYSTEM_TORAM=no
+        ;;
+      live)
+        LIVE=yes
         ;;
       overlay)
         OVERLAY=yes
@@ -281,6 +296,10 @@
     mount_common "$NFS_EXPORT" "$2" "$3,nolock,soft,timeo=3,retrans=2,rsize=32768,wsize=32768,$NFS_OPTIONS" "nfs"
   }
 
+  mount_ubifs() {
+    mount_common "$1" "$2" "$3" "ubifs"
+  }
+
   mount_part() {
     # Mount a local or network filesystem
     # $1:[TYPE=]target, $2:mountpoint, $3:mount options, [$4:fs type]
@@ -288,6 +307,11 @@
 
     MOUNT_TARGET="${1#*=}"
     case $1 in
+      /dev/ubi*)
+        MOUNT_CMD="mount_ubifs"
+        MOUNT_TARGET="$1"
+        RUN_FSCK="no"
+        ;;
       LABEL=*|UUID=*|/*)
         MOUNT_CMD="mount_common"
         MOUNT_TARGET="$1"
@@ -398,28 +422,59 @@
     /bin/busybox reboot
   }
 
+  force_fsck() {
+    echo "Filesystem corruption has been detected"
+    echo "To prevent an automatic repair attempt continuing"
+    echo "press any key or power off your system within the next 120 seconds"
+    echo ""
+    read -t120 -n1
+    # The exit status is 0 if input is available
+    # The exit status is greater than 128 if the timeout is exceeded
+    if [ "$?" -ne "0" -o "$?" -gt "128" ] ; then
+      echo "repairing filesystem.."
+      echo ""
+      /sbin/fsck -T -M -y $RUN_FSCK_DISKS
+      FSCK_RET="$?"
+      if [ "$(( $FSCK_RET & 8 ))" = 8 ] ; then
+        # fubar
+        echo "Forced fsck failed. Your system is broken beyond repair"
+        echo "Please re-install OpenELEC"
+        echo ""
+        echo "Press enter to shutdown now"
+        echo ""
+        read fubar
+        poweroff
+      fi
+      do_reboot
+    else
+      echo "shutting down..."
+      sleep 5
+      sync
+      poweroff
+    fi
+  }
+
   check_disks() {
     if [ "$RUN_FSCK" = "yes" -a -n "$RUN_FSCK_DISKS" ]; then
       progress "Checking disk(s): $RUN_FSCK_DISKS"
         /sbin/fsck -T -M -p -a $RUN_FSCK_DISKS > /dev/null 2>&1
         FSCK_RET="$?"
 
-        case "$FSCK_RET" in
-          0) # no errors found
-            progress "no filesystem errors found, continuing..."
-            ;;
-          1) # filesystem errors corrected
-            progress "filesystem errors corrected , continuing..."
-            ;;
-          2) # reboot needed
-            echo "filesystem repaired, reboot needed..."
-            do_reboot
-            ;;
-          4) # errors left
-            error "could not repair filesystem, dropping to debug shell, try to run 'fsck' manually"
-            do_reboot
-            ;;
-        esac
+        # FSCK_RET is the bit-wise OR of the exit codes for each filesystem that is checked.
+        if [ "$(( $FSCK_RET & 4 ))" = 4 ] ; then
+          # errors left
+          force_fsck
+        elif [ "$(( $FSCK_RET & 2 ))" = 2 ] ; then
+          # reboot needed
+          echo "filesystem repaired, reboot needed..."
+          do_reboot
+        elif [ "$(( $FSCK_RET & 1 ))" = 1 ] ; then
+          # filesystem errors corrected
+          progress "filesystem errors corrected , continuing..."
+        elif [ "$(( $FSCK_RET & 0 ))" = 0 ] ; then
+          # no errors found
+          progress "no filesystem errors found, continuing..."
+        fi
     fi
   }
 
@@ -455,6 +510,12 @@
   mount_storage() {
     progress "Mounting storage"
 
+    if [ "$LIVE" = "yes" ]; then
+      # mount tmpfs and exit early. disk=xx is not allowed in live mode
+      mount -t tmpfs none /storage
+      return
+    fi
+
     wakeonlan
 
     if [ -n "$disk" ]; then
@@ -475,6 +536,9 @@
         fi
       fi
       mount_part "$disk" "/storage" "rw,noatime"
+    else
+      # /storage should always be writable
+      mount -t tmpfs none /storage
     fi
   }
 
@@ -591,10 +655,7 @@
     fi
 
     mount --move /flash /sysroot/flash
-
-    if [ -n "$disk" ]; then
-      mount --move /storage /sysroot/storage
-    fi
+    mount --move /storage /sysroot/storage
 
     if [ ! -d "/sysroot/lib/modules/$(uname -r)/" -a -f "/sysroot/usr/lib/systemd/systemd" ]; then
       echo ""
@@ -630,25 +691,20 @@
 
   BOOT_STEP=final
 
-  # no suspend when booted from nonpersistent storage
+  # log if booting from usb / removable storage
   STORAGE=$(cat /proc/mounts | grep " /sysroot/storage " | awk '{print $1}' | awk -F '/' '{print $3}')
-  if [ -n "$STORAGE" ] ; then
-    removable="/sys/class/block/*/$STORAGE/../removable"
-    if [ -e $removable ] ; then
-      if [ "$(cat $removable 2>/dev/null)" = "1" ] ; then
-        SUSPEND_DISABLED=yes
-      fi
-    fi
-  fi
   FLASH=$(cat /proc/mounts | grep " /sysroot/flash " | awk '{print $1}' | awk -F '/' '{print $3}')
-  if [ -n "$FLASH" ] ; then
-    removable="/sys/class/block/*/$FLASH/../removable"
-    if [ -e $removable ] ; then
-      if [ "$(cat $removable 2>/dev/null)" = "1" ] ; then
-        SUSPEND_DISABLED=yes
+  for i in $STORAGE $FLASH ; do
+    if [ -n "$i" ] ; then
+      removable="/sys/class/block/*/$i/../removable"
+      if [ -e $removable ] ; then
+        if [ "$(cat $removable 2>/dev/null)" = "1" ] ; then
+          echo "### BIG FAT WARNING" > /dev/kmsg
+          echo "### $i is removable. suspend/resume may not work" > /dev/kmsg
+        fi
       fi
     fi
-  fi
+  done
   # move some special filesystems
   /bin/busybox mount --move /dev /sysroot/dev
   /bin/busybox mount --move /proc /sysroot/proc
@@ -662,17 +718,9 @@
   if [ "$STORAGE_NETBOOT" = "yes" ] ; then
     echo "" > /sysroot/dev/.storage_netboot
   fi
-  # no suspend when booted from nonpersistent storage
-  if [ "$SUSPEND_DISABLED" = "yes" ] ; then
-    echo "" > /sysroot/dev/.suspend_disabled
-  fi
 
   if [ -f /sysroot/storage/.please_resize_me ] ; then
     INIT_UNIT="--unit=fs-resize.target"
-  fi
-
-  if [ -f /sysroot/storage/.cache/reset_oe -o -f /sysroot/storage/.cache/reset_xbmc ] ; then
-    INIT_UNIT="--unit=factory-reset.target"
   fi
 
   BACKUP_FILE=`ls -1 /sysroot/storage/.restore/??????????????.tar 2>/dev/null | head -n 1`
@@ -680,6 +728,9 @@
     INIT_UNIT="--unit=backup-restore.target"
   fi
 
+  if [ -f /sysroot/storage/.cache/reset_oe -o -f /sysroot/storage/.cache/reset_xbmc ] ; then
+    INIT_UNIT="--unit=factory-reset.target"
+  fi
   # switch to new sysroot and start real init
   exec /bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS $INIT_UNIT
 
diff --git a/scripts/create_addon b/scripts/create_addon
--- a/scripts/create_addon
+++ b/scripts/create_addon
@@ -1,21 +1,21 @@
 #!/bin/bash
 
 ################################################################################
-#      This file is part of DeKockBlock - http://www.dekockblock.tv
-#      Copyright (C) 2009-2014 Stephan Raue (stephan@dekockblock.tv)
+#      This file is part of OpenELEC - http://www.openelec.tv
+#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
 #
-#  DeKockBlock is free software: you can redistribute it and/or modify
+#  OpenELEC is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation, either version 2 of the License, or
 #  (at your option) any later version.
 #
-#  DeKockBlock is distributed in the hope that it will be useful,
+#  OpenELEC is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.
 #
 #  You should have received a copy of the GNU General Public License
-#  along with DeKockBlock.  If not, see <http://www.gnu.org/licenses/>.
+#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
 ################################################################################
 
 . config/options $1
@@ -30,21 +30,25 @@ if [ -n "$PKG_ARCH" -a ! "$PKG_ARCH" = "any" ]; then
   echo "$PKG_ARCH" | grep -q "\-$TARGET_ARCH" && exit 0
 fi
 
-if [ "$PKG_IS_ADDON" = "yes" ] ; then
-  $SCRIPTS/build $@
-
-  printf  "%${BUILD_INDENT}c CREATE ADDON  $1\n" ' '>&$SILENT_OUT
-  export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))
-
-  rm -rf $ADDON_BUILD
-
-  if [ "$(type -t addon)" = "function" ]; then
-    addon
-  else
-    echo "*** unsupported package format. please convert your package ***"
-    exit 1
+if [ -n "$PKG_ADDON_PROJECTS" -a ! "$PKG_ADDON_PROJECTS" = "any" ]; then
+  for _PROJECT in $PKG_ADDON_PROJECTS ; do
+    if [ "$_PROJECT" = "$PROJECT" ] ; then
+      PROJECT_SUPPORTED="yes"
+    fi
+  done
+  if [ ! "$PROJECT_SUPPORTED" = "yes" ] ; then
+    echo "*** ERROR: $PKG_ADDON_ID: '$PROJECT' not supported ***"
+    exit 0
   fi
+fi
 
+if [ -n "$PKG_ADDON_REPOVERSION" -a ! "$PKG_ADDON_REPOVERSION" = "$ADDON_VERSION" ]; then
+  echo "*** ERROR: $PKG_ADDON_ID: ADDON_VERSION '$ADDON_VERSION' not supported ***"
+  exit 0
+fi
+
+
+pack_addon() {
   IFS=" "
   for i in $PKG_ADDON_REQUIRES; do
     REQUIRES_ADDONNAME=`echo $i | cut -f1 -d ":"`
@@ -55,29 +59,31 @@ if [ "$PKG_IS_ADDON" = "yes" ] ; then
   unset IFS
 
   mkdir -p $ADDON_BUILD/$PKG_ADDON_ID
+
+  if [ ! -f $ADDON_BUILD/$PKG_ADDON_ID/addon.xml ]; then
+    cp config/addon/${PKG_ADDON_TYPE}.xml $ADDON_BUILD/$PKG_ADDON_ID/addon.xml
+    ADDONVER=$ADDON_VERSION.$PKG_REV
+  else
+    if [ ! $(which xmlstarlet) ]; then
+      echo "*** ERROR: $ADDON has addon.xml shipped, you need 'xmlstarlet' ***"
+      exit 255
+    fi
+    ADDONVER=$(xmlstarlet sel -t -v "/addon/@version" $ADDON_BUILD/$PKG_ADDON_ID/addon.xml)
+  fi
+
   if [ -f $PKG_DIR/source/default.py ]; then
     cp -R $PKG_DIR/source/* $ADDON_BUILD/$PKG_ADDON_ID
-  else
-    echo "*** WARNING: You *probably* need at least $PKG_DIR/source/default.py to make your addon work ***"
   fi
 
   if [ -f $PKG_DIR/icon/icon.png ]; then
     cp $PKG_DIR/icon/icon.png $ADDON_BUILD/$PKG_ADDON_ID
-  else
-    echo "*** WARNING: It's recommended to have a $PKG_DIR/icon/icon.png file ***"
   fi
 
   if [ -f $PKG_DIR/changelog.txt ]; then
     cp $PKG_DIR/changelog.txt $ADDON_BUILD/$PKG_ADDON_ID
-  else
-    echo "*** WARNING: It's recommended to have a $PKG_DIR/changelog.txt file ***"
   fi
 
-  if [ ! -f $ADDON_BUILD/$PKG_ADDON_ID/addon.xml ]; then
-    cp config/addon/${PKG_ADDON_TYPE}.xml $ADDON_BUILD/$PKG_ADDON_ID/addon.xml
-  fi
-
-  PROVIDER_NAME="dekockblock.tv"
+  PROVIDER_NAME="openelec.tv"
   if [ ! -z "$PKG_MAINTAINER" ] ; then
     PROVIDER_NAME="$PKG_MAINTAINER"
   fi
@@ -94,22 +100,55 @@ if [ "$PKG_IS_ADDON" = "yes" ] ; then
        -e "s|@PKG_LONGDESC@|$PKG_LONGDESC|g" \
        -e "s|@PKG_DISCLAIMER@|$PKG_DISCLAIMER|g" \
        -e "s|@PROVIDER_NAME@|$PROVIDER_NAME|g" \
+       -e "s|@PKG_ADDON_PROVIDES@|$PKG_ADDON_PROVIDES|g" \
        -i $ADDON_BUILD/$PKG_ADDON_ID/addon.xml
 
   if [ "$2" != "-test" ] ; then
+    ADDON_INSTALL_DIR="$TARGET/$ADDONS/$ADDON_VERSION/$PROJECT/$TARGET_ARCH/$PKG_ADDON_ID"
+    if [ -f $ADDON_INSTALL_DIR/$PKG_ADDON_ID-$ADDONVER.zip ] ; then
+      echo "*** WARNING: $PKG_ADDON_ID-$ADDONVER.zip already exists. not overwriting it ***"
+      return 0
+    fi
     cd $ADDON_BUILD
     echo "*** compressing Addon $PKG_ADDON_ID ... ***"
-    zip -rq $PKG_ADDON_ID-$ADDON_VERSION.$PKG_REV.zip $PKG_ADDON_ID;
+    zip -rq $PKG_ADDON_ID-$ADDONVER.zip $PKG_ADDON_ID;
     cd - &>/dev/null
 
-    ADDON_INSTALL_DIR="$TARGET/$ADDONS/$ADDON_VERSION/$PROJECT/$TARGET_ARCH/$PKG_ADDON_ID"
     mkdir -p $ADDON_INSTALL_DIR
-    cp $ADDON_BUILD/$PKG_ADDON_ID-$ADDON_VERSION.$PKG_REV.zip $ADDON_INSTALL_DIR
-    if [ -f $PKG_DIR/changelog.txt ]; then
-      cp $PKG_DIR/changelog.txt $ADDON_INSTALL_DIR/changelog-$ADDON_VERSION.$PKG_REV.txt
+    cp $ADDON_BUILD/$PKG_ADDON_ID-$ADDONVER.zip $ADDON_INSTALL_DIR
+    if [ -f $ADDON_BUILD/$PKG_ADDON_ID/changelog.txt ]; then
+      cp $ADDON_BUILD/$PKG_ADDON_ID/changelog.txt $ADDON_INSTALL_DIR/changelog-$ADDONVER.txt
     fi
-    if [ -f $PKG_DIR/icon/icon.png ]; then
-      cp $PKG_DIR/icon/icon.png $ADDON_INSTALL_DIR/icon.png
+    if [ -f $ADDON_BUILD/$PKG_ADDON_ID/icon.png ]; then
+      cp $ADDON_BUILD/$PKG_ADDON_ID/icon.png $ADDON_INSTALL_DIR/icon.png
     fi
+  fi
+}
+
+if [ "$PKG_IS_ADDON" = "yes" ] ; then
+  $SCRIPTS/build $@
+
+  printf  "%${BUILD_INDENT}c CREATE ADDON  ($PROJECT/$TARGET_ARCH) $1\n" ' '>&$SILENT_OUT
+  export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))
+
+  rm -rf $ADDON_BUILD
+
+  if [ "$(type -t addon)" = "function" ]; then
+    addon
+  else
+    echo "*** unsupported package format. please convert your package ***"
+    exit 1
+  fi
+
+  # HACK for packages tat provide multiple addons like screensavers.rsxs
+  # addon's addon() in package.mk should take care for exporting
+  # MULTI_ADDONS="addon.boo1 addon.boo2 addon.boo3"
+  if [ -n "$MULTI_ADDONS" ] ; then
+    for _ADDON in $MULTI_ADDONS ; do
+      PKG_ADDON_ID=$_ADDON
+      pack_addon
+    done
+  else
+    pack_addon
   fi
 fi
